version: '3.9'
name: virtual
services:
  bun:
    container_name: virtual-bun
    build:
      dockerfile: ./bun/Dockerfile
    ports:
      - 8080:8080
    networks:
      - backend
networks:
  backend:
    driver: bridge