version: '3.9'
name: virtual
services:
  #############################
  # CODE
  #############################
  code:
    container_name: code
    domainname: $CODE_DOMAIN
    build:
      dockerfile: ./code/Dockerfile
    mem_limit: $AWS_T3_NANO_MEMORY_LIMIT
    cpus: $AWS_T3_NANO_CPUS 
    ports:
      - 8080
    networks:
      - backend

  #############################
  # PROXY
  #############################
  proxy:
    container_name: proxy
    domainname: $PROXY_DOMAIN
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./infrastructure/nginx:/etc/nginx/conf.d
    networks:
      - backend
    depends_on:
      - code
    links:
      - code

  #############################
  # DATABASE
  #############################
  database:
    container_name: database
    domainname: $DATABASE_DOMAIN
    build:
      dockerfile: ./database/Dockerfile
    environment:
      - PGUSER=$POSTGRES_USER
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 3
    mem_limit: $AWS_T3_NANO_MEMORY_LIMIT
    cpus: $AWS_T3_NANO_CPUS
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    depends_on:
      - code
    networks:
      - backend

  #############################
  # DATABASE GUI
  #############################
  database-gui:
    container_name: database-gui
    domainname: $DATABASE_GUI_DOMAIN
    image: dpage/pgadmin4:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 2
        window: 180s
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    depends_on:
      - database
    networks:
      - backend

  #############################
  # CACHE
  #############################
  cache:
    container_name: cache
    domainname: $CACHE_DOMAIN
    image: redis:7.2
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 10
        window: 60s
    ports:
      - "6379:6379"
    volumes:
      - /cache:/root/redis
      - /cache/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_PORT=$REDIS_PORT
      - REDIS_DATABASES=$REDIS_DATABASES
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      retries: 2
      timeout: 5s
    networks:
      - backend

  #############################
  # CACHE-GUI
  #############################
  cache-gui:
    container_name: cache-gui
    domainname: $CACHE_GUI_DOMAIN
    image: rediscommander/redis-commander:latest
    build: .
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 2
        window: 180s
    environment:
    - REDIS_HOSTS=$REDIS_HOSTS
    ports:
    - 8081:8081
    depends_on:
      - cache
    networks:
      - backend

  #############################
  # EVENT-STORE-MANAGER
  #############################   
  event-store-manager:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: $ZOOKEEPER_CLIENT_PORT
      ZOOKEEPER_TICK_TIME: $ZOOKEEPER_TICK_TIME
    ports:
      - 22181:2181

  #############################
  # EVENT-STORE
  #############################   
  event-store:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - event-store-manager
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: $KAFKA_BROKER_ID
      KAFKA_ZOOKEEPER_CONNECT: $KAFKA_ZOOKEEPER_CONNECT
      KAFKA_ADVERTISED_LISTENERS: $KAFKA_ADVERTISED_LISTENERS
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: $KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      KAFKA_INTER_BROKER_LISTENER_NAME: $KAFKA_INTER_BROKER_LISTENER_NAME
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: $KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR

#############################
# VOLUMES
#############################
volumes:
  cache:
    driver: local
  pgdata:

#############################
# NETWORKS
#############################
networks:
  backend:
    driver: bridge